### ISSUE TITLE
Sponsors and supporters

### ISSUE THREAD

**Issue by kira0204** [devil-Coder/itc#3]
- [x] Increase margin between Techloop logo and the text below.
- [x] Use better quality pictures for IEEE MS, ruining the essence of the website.
- [x] Bring both the logos closer
- [x] increase the height of the whole div.

**Comment by devil-Coder** [comment]
@hhk998402 please do the required.

**Comment by hhk998402** [comment]
Have fixed the issue listed above, closing issue for now. If any further improvements are needed, use the other "dontclose" issue
